services:
  countryapi:
    build:
      context: .  # Carpeta actual de Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # exponer puerto 8080
    volumes:
      - ./data:/app/data  # persistencia de datos